name: moor_shared
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dart
  cupertino_icons: ^0.1.2
  moor: ^1.7.1
  rxdart: ^0.22.2
  intl: ^0.16.0

  # Database for mobile and Desktop
  moor_ffi: ^0.0.1
  
  # Helper to find the database path on mobile
  path_provider: ^1.3.0
  path: ^1.6.4

  # Web

dev_dependencies:
  moor_generator: ^1.7.1
  build_runner: ^1.6.7
  build_web_compilers: ^2.3.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  moor:
    git:
      url: git://github.com/simolus3/moor.git
      ref: beta
      path: moor/
  moor_ffi:
    git:
      url: git://github.com/simolus3/moor.git
      ref: beta
      path: moor_ffi/
  moor_generator:
    git:
      url: git://github.com/simolus3/moor.git
      ref: beta
      path: moor_generator/

flutter:
  uses-material-design: true
